# $\color{blue}{\text{FIJI Mask Analysis}}$
### $\color{blue}{\text{average of total sum, total number, and median area of each image}}$

In [7]:
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib as plt
import seaborn as sns
import textwrap
from textwrap import wrap
from scipy.stats import f_oneway

# $$\color{Turquoise}{\text{Input Section}}$$

$\color{Blue}{\text{1) Paste the path link and sheet name for the excel file with the thresholding and/or image info in the following format:}}$

In [11]:
Thresh = pd.read_excel(io="C:/Users/PC/Documents/TEST_FIJI-EXPORTS.xlsx", 
                       sheet_name='Threshold')

$\color{Blue}{\text{2) Paste the path link for the results excel file and enter the sheet name you want to analyse in the same format as above}}$

In [13]:
Var1 = pd.read_excel(io="C:/Users/PC/Documents/TEST_FIJI-EXPORTS.xlsx", 
                     sheet_name='Signal1')

$\color{Blue}{\text{3) Paste just the path link to the excel file you'd like the exports sent to in quotations}}$

In [14]:
export_file = "C:/Users/PC/Documents/TEST_PYTHON-EXPORTS.xlsx"

$\color{Blue}{\text{4) Export sheet names}}$

- $\color{Blue}{\text{if you'd like to use the automatically generated ones, input 'no' and press enter}}$
- $\color{Blue}{\text{if not, input three new sheet names separated by spaces}}$

$\color{Blue}{\text{Example:}}$

$\color{Blue}{\text{SUMS COUNTS MEDIANS}}$

In [15]:
sheetnames = input("Sheet names: ").split()

Sheet names:  no

$\color{Blue}{\text{5) Input the total number of images analysed in the white box and press enter}}$

In [16]:
images = int(input("Number of Images: "))

Number of Images:  96

$\color{Blue}{\text{6) Input the Label Names found in the label columns for each image}}$
- $\color{Blue}{\text{enter just the antibody names exactly as they appear in the file}}$
- $\color{Blue}{\text{enter multiple names in the order they appear in the file from left to right}}$
- $\color{Blue}{\text{separated by a space}}$
- $\color{Blue}{\text{they do not need to be entered in all caps}}$

$\color{Blue}{\text{Ex) Fig 1 entry:}}$

$\color{Blue}{\text{PSD SYN TDP}}$

$\color{Blue}{\text{Ex) Fig 2 entry:}}$

$\color{Blue}{\text{PSD VG1 VG2 PEZ}}$

In [17]:
name = input("Label names: ").split()

Label names:  Signal1 Signal2 Signal3

# $$\color{Aquamarine}{\text{Analysis Code Section}}$$

In [18]:
Thresh1 = Thresh.iloc[0:images].reset_index()
Thresh1['index'] = Thresh1['index'] + 1

name_len = len(name)
step1 = pd.DataFrame(Var1.iloc[1]).reset_index().dropna()
step1a = step1.iloc[0, 1]

if 'Mask' in step1a:
    if name_len == 3:
        step0a = 1
    elif name_len == 4:
        step0a = 2
else:
    if name_len == 1:
        step0a = 3
    elif name_len == 2:
        step0a = 4
    elif name_len == 3:
        step0a = 5

In [19]:
name_len = len(name) 
test = Var1.iloc[0,0:].dropna()
test1 = pd.DataFrame(test)
test2 = pd.DataFrame(test1.describe()).T
test3 = int(test2.iloc[0, 0])
test4 = test3 / name_len
test5 = int(test2.iloc[0, 3])

#num of labels
test6 = int(test2.iloc[0, 1])

#num of images
test7 = test5 / test6

#num of columns per label (including label columns)
test8 = test3 / test7

In [20]:
name_len = len(name)                                  # create column names for the results tables based on number of colocalisation variables 
Thresh_columns = list(Thresh1.columns)
and_name = ' & '
no_name = ' no '
all_name = 'all '

if step0a == 3:
        name1 = name[0].upper()
        Section0 = Thresh_columns+[all_name+name1]
elif step0a == 4:
    name1 = name[0].upper()
    name2 = name[1].upper()
    Section1 = Thresh_columns+[all_name+name1, name1+and_name+name2, name1+no_name+name2]
elif step0a == 5:
    name1 = name[0].upper()
    name2 = name[1].upper()
    name3 = name[2].upper()
    Section2 = Thresh_columns+[all_name+name1, 
                               name1+and_name+name2, 
                               name1+no_name+name2, 
                               name1+and_name+name2+and_name+name3, 
                               name1+and_name+name2+no_name+name3, 
                               name1+and_name+name3+and_name+name2, 
                               name1+no_name+name2+no_name+name3, 
                               name1+and_name+name3, 
                               name1+no_name+name3] 

elif step0a == 1:
    name1 = name[0].upper()
    name2 = name[1].upper()
    name3 = name[2].upper()
    Section3a = Thresh_columns+[name1,
                                name1+and_name+name2,
                                name1+no_name+name2,
                                name1+and_name+name2+and_name+name3,
                                name1+and_name+name2+no_name+name3,
                                name1+and_name+name3,
                                name1+and_name+name3+no_name+name2,
                                name1+no_name+name2+no_name+name3]                                 
elif step0a == 2:
    name1 = name[0].upper()
    name2 = name[1].upper()
    name3 = name[2].upper()
    name4 = name[3].upper()
    Section3 = Thresh_columns+[name1,
                               name1+and_name+name2,
                               name1+and_name+name2+no_name+name3,
                               name1+and_name+name2+no_name+name3+and_name+name4,
                               name1+and_name+name2+no_name+name3+no_name+name4,
                               name1+no_name+name2+no_name+name3+no_name+name4,
                               name1+and_name+name3,
                               name1+no_name+name2+and_name+name3,
                               name1+no_name+name2+and_name+name3+and_name+name4,
                               name1+no_name+name2+and_name+name3+no_name+name4,
                               name1+and_name+name2+and_name+name3+and_name+name4]

In [21]:
Var1.columns = np.arange(len(Var1.columns))
area_columns = pd.DataFrame(Var1.iloc[0][(Var1.iloc[0] == 'Area')].reset_index())
mean_columns = pd.DataFrame(Var1.iloc[0][(Var1.iloc[0] == 'Mean')].reset_index())
keep_columns1 = pd.concat((area_columns, mean_columns), axis=0).sort_values(by='index')
keep_columns2 = list(keep_columns1['index'])

drop_columns1 = Var1.drop(keep_columns2, axis=1).T.reset_index()
drop_columns2 = list(drop_columns1['index'])
final_columns = Var1.drop(drop_columns2, axis=1)
final_columns.columns = final_columns.iloc[0]
Var_table = final_columns.drop(0)
Var_table

,Area,Mean,Area,Mean,Area,Mean,Area,Mean,Area,Mean,...,Area,Mean,Area,Mean,Area,Mean,Area,Mean,Area,Mean
1,0.177,1096.81,0.177,0,0.177,0,0.066,1072.604,0.066,0,...,0.093,23.8,0.093,47.6,0.176,2635.688,0.176,0,0.176,0
2,0.5,718.599,0.5,0,0.5,0,0.176,1892.326,0.176,0,...,0.066,187.642,0.066,0,0.219,2051.847,0.219,0,0.219,0
3,0.086,732.261,0.086,0,0.086,62.826,0.034,1095.259,0.034,0,...,0.06,0,0.06,0,0.164,2594.121,0.164,0,0.164,0
4,0.196,775.414,0.196,0,0.196,32.484,0.04,1048.75,0.04,0,...,0.264,0,0.264,0,0.088,2035.366,0.088,0,0.088,0
5,0.065,1006.173,0.065,0,0.065,19.615,0.137,1436.018,0.137,148.364,...,0.097,0,0.097,0,0.399,2701.834,0.399,0,0.399,1.594
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1538,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
Var_columns = Var_table.iloc[0].count() / images
Var_size = Var_columns.astype(np.int64)
Var_total = Var_table.iloc[0].count()
Column_Names = list(range(1, Var_size + 1))

In [23]:
Var_sums = []

if step0a == 3:
    for i in range(0, Var_total, Var_size):
        Chunk = Var_table.iloc[0:,i:i+Var_size].dropna()
        Chunk1 = Chunk.set_axis(Column_Names, axis='columns') 
        Col_Vars = pd.DataFrame(Chunk1[(Chunk1[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        sums = pd.DataFrame(Col_Vars.sum()).set_axis([i//Var_size + 1], axis='columns').T
        sums_merge = Thresh1.merge(sums, how='inner', left_on='index', right_index=True)
        sums_merge.columns = Section0 
        Var_sums.append(sums_merge)
elif step0a == 4:
    for i in range(0, Var_total, Var_size):
        Chunk = Var_table.iloc[0:,i:i+Var_size].dropna()
        Chunk1 = Chunk.set_axis(Column_Names, axis='columns')    
        Label1 = pd.DataFrame(Chunk1[(Chunk1[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        Label1_Label2 = pd.DataFrame(Chunk1[(Chunk1[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2'], axis='columns')
        Label1_noLabel2 = pd.DataFrame(Chunk1[(Chunk1[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1 no Label2'], axis='columns')
        Col_Vars = pd.concat((Label1, Label1_Label2, Label1_noLabel2), axis=1)
        sums = pd.DataFrame(Col_Vars.sum()).set_axis([i//Var_size + 1], axis='columns').T
        sums_merge = Thresh1.merge(sums, how='inner', left_on='index', right_index=True)
        sums_merge.columns = Section1
        Var_sums.append(sums_merge)
elif step0a == 5:
    for i in range(0, Var_total, Var_size):
        Chunk = Var_table.iloc[0:,i:i+Var_size].dropna()
        Chunk1 = Chunk.set_axis(Column_Names, axis='columns')    
        Label1 = pd.DataFrame(Chunk1[(Chunk1[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        Label1_Label2 = pd.DataFrame(Chunk1[(Chunk1[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2'], axis='columns')
        Label1_noLabel2 = pd.DataFrame(Chunk1[(Chunk1[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1 no Label2'], axis='columns')
        Label1_Label2_Label3 = pd.DataFrame(Chunk1[(Chunk1[4] != 0) & (Chunk1[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-Label3'], axis='columns')
        Label1_Label2_noLabel3 = pd.DataFrame(Chunk1[(Chunk1[4] != 0) & (Chunk1[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2 no Label3'], axis='columns')
        Label1_noLabel2_Label3 = pd.DataFrame(Chunk1[(Chunk1[4] == 0) & (Chunk1[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3 no Label2'], axis='columns')
        Label1_noLabel2_noLabel3 = pd.DataFrame(Chunk1[(Chunk1[4] == 0) & (Chunk1[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1 no Label2 or Label3'], axis='columns')
        Label1_Label3 = pd.DataFrame(Chunk1[(Chunk1[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3'], axis='columns')
        Label1_noLabel3 = pd.DataFrame(Chunk1[(Chunk1[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1 no Label3'], axis='columns')

        Col_Vars = pd.concat((Label1,
                              Label1_Label2,
                              Label1_noLabel2,
                              Label1_Label2_Label3,
                              Label1_Label2_noLabel3,
                              Label1_noLabel2_Label3,
                              Label1_noLabel2_noLabel3,
                              Label1_Label3,
                              Label1_noLabel3),
                              axis=1)
        sums = pd.DataFrame(Col_Vars.sum()).set_axis([i//Var_size + 1], axis='columns').T
        sums_merge = Thresh1.merge(sums, how='inner', left_on='index', right_index=True)
        sums_merge.columns = Section2
        Var_sums.append(sums_merge)
elif step0a == 2:
    for i in range(0, Var_total, Var_size):
        Chunk = Var_table.iloc[0:,i:i+Var_size].dropna()
        Chunk1 = Chunk.set_axis(Column_Names, axis='columns')
        Label1 = pd.DataFrame(Chunk1.iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        Label1_Label2 = pd.DataFrame(Chunk1[(Chunk1[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label2'], axis='columns')
        Label1_Label2_noLabel3 = pd.DataFrame(Chunk1[(Chunk1[2] != 0) & (Chunk1[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3'], axis='columns')
        Label1_Label2_noLabel3_Label4 = pd.DataFrame(Chunk1[(Chunk1[2] != 0) & (Chunk1[4] == 0) & (Chunk1[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3-Label4'], axis='columns')
        Label1_Label2_noLabel3_noLabel4 = pd.DataFrame(Chunk1[(Chunk1[2] != 0) & (Chunk1[4] == 0) & (Chunk1[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3-noLabel4'], axis='columns')
        Label1_noLabel2_noLabel3_noLabel4 = pd.DataFrame(Chunk1[(Chunk1[2] == 0) & (Chunk1[4] == 0) & (Chunk1[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-noLabel2-noLabel3-noLabel4'], axis='columns')
        
        Label1_Label3 = pd.DataFrame(Chunk1[(Chunk1[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label3'], axis='columns')
        Label1_Label3_noLabel2 = pd.DataFrame(Chunk1[(Chunk1[2] == 0) & (Chunk1[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2'], axis='columns')
        Label1_Label3_noLabel2_Label4 = pd.DataFrame(Chunk1[(Chunk1[2] == 0) & (Chunk1[4] != 0) & (Chunk1[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2-Label4'], axis='columns')
        Label1_Label3_noLabel2_noLabel4 = pd.DataFrame(Chunk1[(Chunk1[2] == 0) & (Chunk1[4] != 0) & (Chunk1[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2-noLabel4'], axis='columns')
        Label1_Label2_Label3_Label4 = pd.DataFrame(Chunk1[(Chunk1[2] != 0) & (Chunk1[4] != 0) & (Chunk1[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-noLabel3-noLabel2-noLabel4'], axis='columns')
        
        Col_Vars = pd.concat((Label1,
                              Label1_Label2,
                              Label1_Label2_noLabel3,
                              Label1_Label2_noLabel3_Label4,
                              Label1_Label2_noLabel3_noLabel4,
                              Label1_noLabel2_noLabel3_noLabel4,
                              Label1_Label3,
                              Label1_Label3_noLabel2,
                              Label1_Label3_noLabel2_Label4,
                              Label1_Label3_noLabel2_noLabel4,
                              Label1_Label2_Label3_Label4), axis=1)
        sums = pd.DataFrame(Col_Vars.sum()).set_axis([i//Var_size + 1], axis='columns').T
        sums_merge = Thresh1.merge(sums, how='inner', left_on='index', right_index=True)
        sums_merge.columns = Section3
        Var_sums.append(sums_merge)
else:
    for i in range(0, Var_total, Var_size):
        Chunk = Var_table.iloc[0:,i:i+Var_size].dropna()
        Chunk1 = Chunk.set_axis(Column_Names, axis='columns')
        Label1 = pd.DataFrame(Chunk1.iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        Label1_Label2 = pd.DataFrame(Chunk1[(Chunk1[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label2'], axis='columns')
        Label1_noLabel2 = pd.DataFrame(Chunk1[(Chunk1[2] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_noLabel2'], axis='columns')
        Label1_Label2_Label3 = pd.DataFrame(Chunk1[(Chunk1[2] != 0) & (Chunk1[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-Label3'], axis='columns')
        Label1_Label2_noLabel3 = pd.DataFrame(Chunk1[(Chunk1[2] != 0) & (Chunk1[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3'], axis='columns')
        Label1_Label3 = pd.DataFrame(Chunk1[(Chunk1[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label3'], axis='columns')
        Label1_Label3_noLabel2 = pd.DataFrame(Chunk1[(Chunk1[4] != 0) & (Chunk1[2] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2'], axis='columns')
        Label1_noLabel3_noLabel2 = pd.DataFrame(Chunk1[(Chunk1[2] == 0) & (Chunk1[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-noLabel2-noLabel3'], axis='columns')
        Col_Vars = pd.concat((Label1,
                              Label1_Label2,
                              Label1_noLabel2, 
                              Label1_Label2_Label3, 
                              Label1_Label2_noLabel3, 
                              Label1_Label3, 
                              Label1_Label3_noLabel2, 
                              Label1_noLabel3_noLabel2), axis=1)
        
        sums = pd.DataFrame(Col_Vars.sum()).set_axis([i//Var_size + 1], axis='columns').T
        sums_merge = Thresh1.merge(sums, how='inner', left_on='index', right_index=True)
        sums_merge.columns = Section3a
        Var_sums.append(sums_merge)
        

SUMS = pd.DataFrame(pd.concat(Var_sums, ignore_index=False))
SUMS

,index,Mouse,Sex,Genotype,File,Signal1,Signal2,Signal3,all SIGNAL1,SIGNAL1 & SIGNAL2,SIGNAL1 no SIGNAL2,SIGNAL1 & SIGNAL2 & SIGNAL3,SIGNAL1 & SIGNAL2 no SIGNAL3,SIGNAL1 & SIGNAL3 & SIGNAL2,SIGNAL1 no SIGNAL2 no SIGNAL3,SIGNAL1 & SIGNAL3,SIGNAL1 no SIGNAL3
0,1,2940,F,Disease,1A1,463,5017,795,131.557,63.688,67.869,29.777,33.911,21.466,46.403,51.243,80.314
1,2,2940,F,Disease,1A2,159,2499,933,133.222,54.833,78.389,15.283,39.55,20.449,57.94,35.732,97.49
2,3,2940,F,Disease,1A3,148,6118,577,132.616,38.386,94.23,15.744,22.642,20.578,73.652,36.322,96.294
3,4,2940,F,Disease,1A4,440,2424,809,176.825,64.193,112.632,27.458,36.735,35.96,76.672,63.418,113.407
4,5,2940,F,Disease,1B1,367,3165,897,147.641,52.097,95.544,18.384,33.713,23.321,72.223,41.705,105.936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,2956,F,Control,13A4,144,4412,958,166.983,38.385,128.598,18.619,19.766,47.741,80.857,66.36,100.623
92,93,2956,F,Control,13B1,437,3067,766,124.831,56.095,68.736,27.402,28.693,22.221,46.515,49.623,75.208
93,94,2956,F,Control,13B2,161,665,625,125.481,38.219,87.262,16.791,21.428,30.091,57.171,46.882,78.599
94,95,2956,F,Control,13B3,319,2841,1083,62.584,13.841,48.743,7.14,6.701,14.169,34.574,21.309,41.275
95,96,2956,F,Control,13B4,402,2247,920,87.827,17.896,69.931,4.073,13.823,20.306,49.625,24.379,63.448

In [24]:
Var_counts = []

if step0a == 3:
    for j in range(0, Var_total, Var_size):
        Chunk2 = Var_table.iloc[0:,j:j+Var_size].dropna()
        Chunk3 = Chunk2.set_axis(Column_Names, axis='columns')
        Col_Vars1 = pd.DataFrame(Chunk3[(Chunk3[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        counts = pd.DataFrame(Col_Vars1.count()).set_axis([j//Var_size + 1], axis='columns').T
        counts_merge = Thresh1.merge(counts, how='inner', left_on='index', right_index=True)
        counts_merge.columns = Section0
        Var_counts.append(counts_merge)
elif step0a == 4:
    for j in range(0, Var_total, Var_size):
        Chunk2 = Var_table.iloc[0:,j:j+Var_size].dropna()
        Chunk3 = Chunk2.set_axis(Column_Names, axis='columns')
        CLabel1 = pd.DataFrame(Chunk3[(Chunk3[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        CLabel1_Label2 = pd.DataFrame(Chunk3[(Chunk3[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2'], axis='columns')
        CLabel1_noLabel2 = pd.DataFrame(Chunk3[(Chunk3[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1 no Label2'], axis='columns')
        Col_Vars1 = pd.concat((CLabel1, CLabel1_Label2, CLabel1_noLabel2), axis=1)
        counts = pd.DataFrame(Col_Vars1.count()).set_axis([j//Var_size + 1], axis='columns').T
        counts_merge = Thresh1.merge(counts, how='inner', left_on='index', right_index=True)
        counts_merge.columns = Section1
        Var_counts.append(counts_merge)
elif step0a == 5:
    for j in range(0, Var_total, Var_size):
        Chunk2 = Var_table.iloc[0:,j:j+Var_size].dropna()
        Chunk3 = Chunk2.set_axis(Column_Names, axis='columns')
        CLabel1 = pd.DataFrame(Chunk3[(Chunk3[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        CLabel1_Label2 = pd.DataFrame(Chunk3[(Chunk3[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2'], axis='columns')
        CLabel1_noLabel2 = pd.DataFrame(Chunk3[(Chunk3[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1 no Label2'], axis='columns')
        CLabel1_Label3 = pd.DataFrame(Chunk3[(Chunk3[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3'], axis='columns')
        CLabel1_noLabel3 = pd.DataFrame(Chunk3[(Chunk3[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1 no Label3'], axis='columns')
        CLabel1_Label2_Label3 = pd.DataFrame(Chunk3[(Chunk3[4] != 0) & (Chunk3[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-Label3'], axis='columns')
        CLabel1_Label2_noLabel3 = pd.DataFrame(Chunk3[(Chunk3[4] != 0) & (Chunk3[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2 no Label3'], axis='columns')
        CLabel1_noLabel2_Label3 = pd.DataFrame(Chunk3[(Chunk3[4] == 0) & (Chunk3[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3 no Label2'], axis='columns')
        CLabel1_noLabel2_noLabel3 = pd.DataFrame(Chunk3[(Chunk3[4] == 0) & (Chunk3[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1 no Label2 or Label3'], axis='columns')
        Col_Vars1 = pd.concat((CLabel1,
                              CLabel1_Label2,
                              CLabel1_noLabel2,
                              CLabel1_Label2_Label3,
                              CLabel1_Label2_noLabel3,
                              CLabel1_noLabel2_Label3,
                              CLabel1_noLabel2_noLabel3,
                              CLabel1_Label3,
                              CLabel1_noLabel3), axis=1)
        counts = pd.DataFrame(Col_Vars1.count()).set_axis([j//Var_size + 1], axis='columns').T
        counts_merge = Thresh1.merge(counts, how='inner', left_on='index', right_index=True)
        counts_merge.columns = Section2
        Var_counts.append(counts_merge)
elif step0a == 2:
    for j in range(0, Var_total, Var_size):
        Chunk2 = Var_table.iloc[0:,j:j+Var_size].dropna()
        Chunk3 = Chunk2.set_axis(Column_Names, axis='columns')
        CLabel1 = pd.DataFrame(Chunk3.iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        CLabel1_Label2 = pd.DataFrame(Chunk3[(Chunk3[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label2'], axis='columns')
        CLabel1_Label2_noLabel3 = pd.DataFrame(Chunk3[(Chunk3[2] != 0) & (Chunk3[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3'], axis='columns')
        CLabel1_Label2_noLabel3_Label4 = pd.DataFrame(Chunk3[(Chunk3[2] != 0) & (Chunk3[4] == 0) & (Chunk3[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3-Label4'], axis='columns')
        CLabel1_Label2_noLabel3_noLabel4 = pd.DataFrame(Chunk3[(Chunk3[2] != 0) & (Chunk3[4] == 0) & (Chunk3[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3-noLabel4'], axis='columns')
        CLabel1_noLabel2_noLabel3_noLabel4 = pd.DataFrame(Chunk3[(Chunk3[2] == 0) & (Chunk3[4] == 0) & (Chunk3[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-noLabel2-noLabel3-noLabel4'], axis='columns')
        
        CLabel1_Label3 = pd.DataFrame(Chunk3[(Chunk3[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label3'], axis='columns')
        CLabel1_Label3_noLabel2 = pd.DataFrame(Chunk3[(Chunk3[4] != 0) & (Chunk3[2] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2'], axis='columns')
        CLabel1_Label3_noLabel2_Label4 = pd.DataFrame(Chunk3[(Chunk3[4] != 0) & (Chunk3[2] == 0) & (Chunk3[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2-Label4'], axis='columns')
        CLabel1_Label3_noLabel2_noLabel4 = pd.DataFrame(Chunk3[(Chunk3[4] != 0) & (Chunk3[2] == 0) & (Chunk3[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2-noLabel4'], axis='columns')
        CLabel1_Label2_Label3_Label4 = pd.DataFrame(Chunk3[(Chunk3[4] != 0) & (Chunk3[2] != 0) & (Chunk3[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-noLabel3-noLabel2-noLabel4'], axis='columns')
        
        
        Col_Vars1 = pd.concat((CLabel1,
                               CLabel1_Label2,
                               CLabel1_Label2_noLabel3,
                               CLabel1_Label2_noLabel3_Label4,
                               CLabel1_Label2_noLabel3_noLabel4,
                               CLabel1_noLabel2_noLabel3_noLabel4,
                               CLabel1_Label3,
                               CLabel1_Label3_noLabel2,
                               CLabel1_Label3_noLabel2_Label4,
                               CLabel1_Label3_noLabel2_noLabel4,
                               CLabel1_Label2_Label3_Label4), axis=1)
        counts = pd.DataFrame(Col_Vars1.count()).set_axis([j//Var_size + 1], axis='columns').T
        counts_merge = Thresh1.merge(counts, how='inner', left_on='index', right_index=True)
        counts_merge.columns = Section3
        Var_counts.append(counts_merge)
else:
    for j in range(0, Var_total, Var_size):
        Chunk2 = Var_table.iloc[0:,j:j+Var_size].dropna()
        Chunk3 = Chunk2.set_axis(Column_Names, axis='columns')
        CLabel1 = pd.DataFrame(Chunk3.iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        CLabel1_Label2 = pd.DataFrame(Chunk3[(Chunk3[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label2'], axis='columns')
        CLabel1_noLabel2 = pd.DataFrame(Chunk3[(Chunk3[2] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_noLabel2'], axis='columns')
        CLabel1_Label2_Label3 = pd.DataFrame(Chunk3[(Chunk3[2] != 0) & (Chunk3[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-Label3'], axis='columns')
        CLabel1_Label2_noLabel3 = pd.DataFrame(Chunk3[(Chunk3[2] != 0) & (Chunk3[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3'], axis='columns')
        CLabel1_Label3 = pd.DataFrame(Chunk3[(Chunk3[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label3'], axis='columns')
        CLabel1_Label3_noLabel2 = pd.DataFrame(Chunk3[(Chunk3[4] != 0) & (Chunk3[2] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2'], axis='columns')
        CLabel1_noLabel3_noLabel2 = pd.DataFrame(Chunk3[(Chunk3[2] == 0) & (Chunk3[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-noLabel2-noLabel3'], axis='columns')
        Col_Vars1 = pd.concat((CLabel1,
                               CLabel1_Label2,
                               CLabel1_noLabel2, 
                               CLabel1_Label2_Label3, 
                               CLabel1_Label2_noLabel3, 
                               CLabel1_Label3, 
                               CLabel1_Label3_noLabel2, 
                               CLabel1_noLabel3_noLabel2), axis=1)
        
        counts = pd.DataFrame(Col_Vars1.count()).set_axis([j//Var_size + 1], axis='columns').T
        counts_merge = Thresh1.merge(counts, how='inner', left_on='index', right_index=True)
        counts_merge.columns = Section3a
        Var_counts.append(counts_merge)

COUNTS = pd.DataFrame(pd.concat(Var_counts, ignore_index=False))
COUNTS

,index,Mouse,Sex,Genotype,File,Signal1,Signal2,Signal3,all SIGNAL1,SIGNAL1 & SIGNAL2,SIGNAL1 no SIGNAL2,SIGNAL1 & SIGNAL2 & SIGNAL3,SIGNAL1 & SIGNAL2 no SIGNAL3,SIGNAL1 & SIGNAL3 & SIGNAL2,SIGNAL1 no SIGNAL2 no SIGNAL3,SIGNAL1 & SIGNAL3,SIGNAL1 no SIGNAL3
0,1,2940,F,Disease,1A1,463,5017,795,903,382,521,148,234,128,393,276,627
1,2,2940,F,Disease,1A2,159,2499,933,989,358,631,89,269,128,503,217,772
2,3,2940,F,Disease,1A3,148,6118,577,1096,273,823,85,188,136,687,221,875
3,4,2940,F,Disease,1A4,440,2424,809,1261,391,870,129,262,225,645,354,907
4,5,2940,F,Disease,1B1,367,3165,897,1192,344,848,99,245,176,672,275,917
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,2956,F,Control,13A4,144,4412,958,1349,228,1121,87,141,344,777,431,918
92,93,2956,F,Control,13B1,437,3067,766,973,359,614,144,215,155,459,299,674
93,94,2956,F,Control,13B2,161,665,625,1027,264,763,93,171,198,565,291,736
94,95,2956,F,Control,13B3,319,2841,1083,507,88,419,37,51,88,331,125,382
95,96,2956,F,Control,13B4,402,2247,920,746,134,612,22,112,128,484,150,596

In [25]:
Var_medians = []

if step0a == 3:
    for k in range(0, Var_total, Var_size):
        Chunk4 = Var_table.iloc[0:,k:k+Var_size].dropna()
        Chunk5 = Chunk4.set_axis(Column_Names, axis='columns')
        Col_Vars2 = pd.DataFrame(Chunk5[(Chunk5[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1'], axis='columns')
        medians = pd.DataFrame(Col_Vars2.median()).set_axis([k//Var_size + 1], axis='columns').T
        medians_merge = Thresh1.merge(medians, how='inner', left_on='index', right_index=True) 
        medians_merge.columns = Section0
        Var_medians.append(medians_merge)
elif step0a == 4:
    for k in range(0, Var_total, Var_size):
        Chunk4 = Var_table.iloc[0:,k:k+Var_size].dropna()
        Chunk5 = Chunk4.set_axis(Column_Names, axis='columns')
        MLabel1 = pd.DataFrame(Chunk5[(Chunk5[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1'], axis='columns')
        MLabel1_Label2 = pd.DataFrame(Chunk5[(Chunk5[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1_L2'], axis='columns')
        MLabel1_noLabel2 = pd.DataFrame(Chunk5[(Chunk5[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1 noL2'], axis='columns')
        Col_Vars2 = pd.concat((MLabel1, MLabel1_Label2, MLabel1_noLabel2), axis=1)
        medians = pd.DataFrame(Col_Vars2.median()).set_axis([k//Var_size + 1], axis='columns').T
        medians_merge = Thresh1.merge(medians, how='inner', left_on='index', right_index=True)
        medians_merge.columns = Section1
        Var_medians.append(medians_merge)
elif step0a == 5:
    for k in range(0, Var_total, Var_size):
        Chunk4 = Var_table.iloc[0:,k:k+Var_size].dropna()
        Chunk5 = Chunk4.set_axis(Column_Names, axis='columns')
        MLabel1 = pd.DataFrame(Chunk5[(Chunk5[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1'], axis='columns')
        MLabel1_Label2 = pd.DataFrame(Chunk5[(Chunk5[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1_L2'], axis='columns')
        MLabel1_noLabel2 = pd.DataFrame(Chunk5[(Chunk5[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1 noL2'], axis='columns')
        MLabel1_Label3 = pd.DataFrame(Chunk5[(Chunk5[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1_L3'], axis='columns')
        MLabel1_noLabel3 = pd.DataFrame(Chunk5[(Chunk5[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1_noL3'], axis='columns')
        MLabel1_Label2_Label3 = pd.DataFrame(Chunk5[(Chunk5[4] != 0) & (Chunk5[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1_L2_L3'], axis='columns')
        MLabel1_Label2_noLabel3 = pd.DataFrame(Chunk5[(Chunk5[4] != 0) & (Chunk5[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1_L2 noL3'], axis='columns')
        MLabel1_noLabel2_Label3 = pd.DataFrame(Chunk5[(Chunk5[4] == 0) & (Chunk5[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1_L3 noL2'], axis='columns')
        MLabel1_noLabel2_noLabel3 = pd.DataFrame(Chunk5[(Chunk5[4] == 0) & (Chunk5[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['L1 noL2 noL3'], axis='columns')

        Col_Vars2 = pd.concat((MLabel1,
                               MLabel1_Label2,
                               MLabel1_noLabel2,
                               MLabel1_Label2_Label3,
                               MLabel1_Label2_noLabel3,
                               MLabel1_noLabel2_Label3,
                               MLabel1_noLabel2_noLabel3,
                               MLabel1_Label3,
                               MLabel1_noLabel3), axis=1)
        
        medians = pd.DataFrame(Col_Vars2.median()).set_axis([k//Var_size + 1], axis='columns').T
        medians_merge = Thresh1.merge(medians, how='inner', left_on='index', right_index=True)    
        medians_merge.columns = Section2
        Var_medians.append(medians_merge)

elif step0a == 2:
    for k in range(0, Var_total, Var_size):
        Chunk4 = Var_table.iloc[0:,k:k+Var_size].dropna()
        Chunk5 = Chunk4.set_axis(Column_Names, axis='columns')
        MLabel1 = pd.DataFrame(Chunk5.iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        MLabel1_Label2 = pd.DataFrame(Chunk5[(Chunk5[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label2'], axis='columns')
        MLabel1_Label2_noLabel3 = pd.DataFrame(Chunk5[(Chunk5[2] != 0) & (Chunk5[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3'], axis='columns')
        MLabel1_Label2_noLabel3_Label4 = pd.DataFrame(Chunk5[(Chunk5[2] != 0) & (Chunk5[4] == 0) & (Chunk5[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3-Label4'], axis='columns')
        MLabel1_Label2_noLabel3_noLabel4 = pd.DataFrame(Chunk5[(Chunk5[2] != 0) & (Chunk5[4] == 0) & (Chunk5[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3-noLabel4'], axis='columns')
        MLabel1_noLabel2_noLabel3_noLabel4 = pd.DataFrame(Chunk5[(Chunk5[2] == 0) & (Chunk5[4] == 0) & (Chunk5[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-noLabel2-noLabel3-noLabel4'], axis='columns')
        
        MLabel1_Label3 = pd.DataFrame(Chunk5[(Chunk5[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label3'], axis='columns')
        MLabel1_Label3_noLabel2 = pd.DataFrame(Chunk5[(Chunk5[4] != 0) & (Chunk5[2] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2'], axis='columns')
        MLabel1_Label3_noLabel2_Label4 = pd.DataFrame(Chunk5[(Chunk5[4] != 0) & (Chunk5[2] == 0) & (Chunk5[6] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2-Label4'], axis='columns')
        MLabel1_Label3_noLabel2_noLabel4 = pd.DataFrame(Chunk5[(Chunk5[4] != 0) & (Chunk5[2] == 0) & (Chunk5[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2-noLabel4'], axis='columns')
        MLabel1_Label2_Label3_Label4 = pd.DataFrame(Chunk5[(Chunk5[4] == 0) & (Chunk5[2] == 0) & (Chunk5[6] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-noLabel3-noLabel2-noLabel4'], axis='columns')
        
        
        Col_Vars2 = pd.concat((MLabel1,
                               MLabel1_Label2,
                               MLabel1_Label2_noLabel3,
                               MLabel1_Label2_noLabel3_Label4,
                               MLabel1_Label2_noLabel3_noLabel4,
                               MLabel1_noLabel2_noLabel3_noLabel4,
                               MLabel1_Label3,
                               MLabel1_Label3_noLabel2,
                               MLabel1_Label3_noLabel2_Label4,
                               MLabel1_Label3_noLabel2_noLabel4,
                               MLabel1_Label2_Label3_Label4), axis=1)

        medians = pd.DataFrame(Col_Vars2.median()).set_axis([k//Var_size + 1], axis='columns').T
        medians_merge = Thresh1.merge(medians, how='inner', left_on='index', right_index=True)    
        medians_merge.columns = Section3
        Var_medians.append(medians_merge)

else:
    for k in range(0, Var_total, Var_size):
        Chunk4 = Var_table.iloc[0:,k:k+Var_size].dropna()
        Chunk5 = Chunk4.set_axis(Column_Names, axis='columns') 
        MLabel1 = pd.DataFrame(Chunk5.iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1'], axis='columns')
        MLabel1_Label2 = pd.DataFrame(Chunk5[(Chunk5[2] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label2'], axis='columns')
        MLabel1_noLabel2 = pd.DataFrame(Chunk5[(Chunk5[2] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_noLabel2'], axis='columns')
        MLabel1_Label2_Label3 = pd.DataFrame(Chunk5[(Chunk5[2] != 0) & (Chunk5[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-Label3'], axis='columns')
        MLabel1_Label2_noLabel3 = pd.DataFrame(Chunk5[(Chunk5[2] != 0) & (Chunk5[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label2-noLabel3'], axis='columns')
        MLabel1_Label3 = pd.DataFrame(Chunk5[(Chunk5[4] != 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1_Label3'], axis='columns')
        MLabel1_Label3_noLabel2 = pd.DataFrame(Chunk5[(Chunk5[4] != 0) & (Chunk5[2] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-Label3-noLabel2'], axis='columns')
        MLabel1_noLabel3_noLabel2 = pd.DataFrame(Chunk5[(Chunk5[2] == 0) & (Chunk5[4] == 0)].iloc[0:,0].reset_index().iloc[0:,1]).set_axis(['Label1-noLabel2-noLabel3'], axis='columns')
        Col_Vars2 = pd.concat((MLabel1,
                               MLabel1_Label2,
                               MLabel1_noLabel2, 
                               MLabel1_Label2_Label3, 
                               MLabel1_Label2_noLabel3, 
                               MLabel1_Label3, 
                               MLabel1_Label3_noLabel2, 
                               MLabel1_noLabel3_noLabel2), axis=1)
        
        medians = pd.DataFrame(Col_Vars2.median()).set_axis([k//Var_size + 1], axis='columns').T
        medians_merge = Thresh1.merge(medians, how='inner', left_on='index', right_index=True)    
        medians_merge.columns = Section3a
        Var_medians.append(medians_merge)

MEDIANS = pd.DataFrame(pd.concat(Var_medians, ignore_index=False))
MEDIANS

,index,Mouse,Sex,Genotype,File,Signal1,Signal2,Signal3,all SIGNAL1,SIGNAL1 & SIGNAL2,SIGNAL1 no SIGNAL2,SIGNAL1 & SIGNAL2 & SIGNAL3,SIGNAL1 & SIGNAL2 no SIGNAL3,SIGNAL1 & SIGNAL3 & SIGNAL2,SIGNAL1 no SIGNAL2 no SIGNAL3,SIGNAL1 & SIGNAL3,SIGNAL1 no SIGNAL3
0,1,2940,F,Disease,1A1,463,5017,795,0.11,0.1365,0.098,0.159,0.1085,0.1285,0.095,0.15,0.1
1,2,2940,F,Disease,1A2,159,2499,933,0.105,0.122,0.093,0.136,0.12,0.1165,0.09,0.122,0.101
2,3,2940,F,Disease,1A3,148,6118,577,0.096,0.11,0.091,0.153,0.098,0.12,0.086,0.133,0.087
3,4,2940,F,Disease,1A4,440,2424,809,0.107,0.125,0.093,0.164,0.117,0.12,0.088,0.127,0.097
4,5,2940,F,Disease,1B1,367,3165,897,0.103,0.132,0.093,0.171,0.118,0.114,0.088,0.133,0.097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92,2956,F,Control,13A4,144,4412,958,0.098,0.1395,0.093,0.194,0.12,0.1175,0.083,0.125,0.086
92,93,2956,F,Control,13B1,437,3067,766,0.1,0.125,0.085,0.1575,0.106,0.118,0.077,0.137,0.087
93,94,2956,F,Control,13B2,161,665,625,0.096,0.116,0.09,0.147,0.102,0.1155,0.082,0.127,0.086
94,95,2956,F,Control,13B3,319,2841,1083,0.096,0.124,0.088,0.161,0.105,0.1215,0.083,0.132,0.087
95,96,2956,F,Control,13B4,402,2247,920,0.0865,0.096,0.0855,0.1545,0.0855,0.113,0.078,0.1205,0.081

In [26]:
if sheetnames != ['no']:
    auto_sheet_name1 = sheetnames[0]
    auto_sheet_name2 = sheetnames[1]
    auto_sheet_name3 = sheetnames[2]
elif sheetnames == ['no']:
    if name_len > 1:
        auto_sheet_name1 = name[0].upper()+' Mask Sums'
        auto_sheet_name2 = name[0].upper()+' Mask Counts'
        auto_sheet_name3 = name[0].upper()+' Mask Medians'
    elif name_len == 1:
        auto_sheet_name1 = all_name+name[0].upper()+' Sums'
        auto_sheet_name2 = all_name+name[0].upper()+' Counts'
        auto_sheet_name3 = all_name+name[0].upper()+' Medians'

# $$\color{blue}{\text{Export Section}}$$

In [27]:
with pd.ExcelWriter(export_file, mode='a', if_sheet_exists='replace') as writer:  
    SUMS.to_excel(writer, sheet_name=auto_sheet_name1)
    COUNTS.to_excel(writer, sheet_name=auto_sheet_name2)
    MEDIANS.to_excel(writer, sheet_name=auto_sheet_name3)